fix(@nguniversal/builders): make prerender work with large route lists
angular/universal pull request #2105
Opened 2021-05-13 02:55 UTC by sierkov

This is a fix for the issue described in: https://github.com/angular/universal/issues/2067

2021-05-13 04:43 UTC, alan-agius4 requested changes
Why not simply read the index file from the worker?

In general, I'd also want to refactor this in the future and use jest-worker, like we do in https://github.com/angular/universal/blob/master/modules/builders/src/static-generator/index.ts

2021-05-13 05:06 UTC, sierkov commented
That part that passes the index file by value I have copied from the original code.
My best guess it is done that way because the author wanted all of the following at the same time:
1. add a comment "This page was prerendered with Angular Universal" into the output HTML file;
2. not to change the original source index file.
3. not to introduce an additional API parameter for the render, such as "buildComment", etc.
However, I'm new to the code base, so that's just IMHO.

Let me know you'd like to proceed. Should we change that part or keep it?

2021-05-13 05:27 UTC, alan-agius4 commented
The additional of comment can be done directly in the worker, without adding an addition parameter.  The comment doesn't need to be passed on to the worker. 


I believe the intention here was to avoid additional FS reads, but now with your suggested change it is made obsolete.

2021-05-13 05:54 UTC, sierkov commented
I see. Thanks for the explanation. I have found one more dependency at line 113 of the original index.ts:
<pre>
if (normalizedStylesOptimization.inlineCritical) {
      // Workaround for https://github.com/GoogleChromeLabs/critters/issues/64
      indexHtml = indexHtml.replace(
        / media=\"print\" onload=\"this\.media='all'"><noscript><link .+?><\/noscript>/g,
        '>',
      );
}
</pre>

Would you like me to move all of the index.html processing to render.ts: adding the comment + normalizedStylesOptimization.inlineCritical?
I see that render.ts already does some postprocessing, so it would make sense to have it all in one place.

2021-05-13 06:05 UTC, alan-agius4 commented
Yes please.

2021-05-13 06:51 UTC, sierkov commented
Done. LMK

2021-05-13 08:04 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +              `render-args-${process.pid}-${shardIndex}.json`,
Do we still need this? consider we remove a large part of the content from the args by removing the index file? 

If so, we should really move and use jest-workers instead or at least as an interim until we move towards that we use an IPC channel to communicate with the child process. I am not very keen in creating this temporary file. As this feels like a workaround rather than a proper fix.

2021-05-13 08:05 UTC, alan-agius4 requested changes
Thanks a lot for your contribution. Kindly see the feedback left.

2021-05-14 08:13 UTC, sierkov commented on modules/builders/src/prerender/index.ts
> +              `render-args-${process.pid}-${shardIndex}.json`,
I have not yet worked with jest-workers, so I am not able to comment on that immediately. As I understand, that looks like a simple and quick change to you, right?

Regarding the file and IPC, here are my thoughts:
1. My primary objective is to allow for much larger route lists: think 100k, 1M, or even 10M. That's where my current project is moving. In this case, even the reasonably large command-line-argument limit of Linux is not sufficient. So, replacing the file back with command line arguments is a no go.
2. Regarding other IPC methods (I assume one of shared memory, pipes, sockets, or SysV message passing), our case is more of initialization/configuration rather than a true IPC since we pass the arguments only one-way and do not need a response. A configuration file is a reasonable solution in this case event if it is a dynamic one. The only downside that I can see is the risk of the temporary file sticking when the parent process terminates abruptly. Since the file is stored in a temporary directory itself, IMHO, it's not a huge risk.

I understand where you are coming from - you need to maintain this codebase going forward, while I'm just trying to quickly fix one annoying issue. My concern is that the more changes I make in this patch, the more likely I to introduce some hard-to-see bug, since I'm new to this code base and can easily be not aware of some implicit requirements.

I can still take a look at jest-workers over next few days if you believe that will be a simple change. LMK

2021-05-16 22:32 UTC, sierkov commented
@alan-agius4, I'm waiting for your feedback regarding the next steps. JFYI

2021-05-17 15:32 UTC, alan-agius4 commented
> @alan-agius4, I'm waiting for your feedback regarding the next steps. JFYI

I’ll try to get back to this in the coming days

2021-05-17 15:51 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +              `render-args-${process.pid}-${shardIndex}.json`,
Yeah, using jest-worker should be pretty straight forward and we are already using them in a similar fashion. See: https://github.com/angular/universal/blob/master/modules/builders/src/prerender/index.ts

I think this would be easier than using an IPC channel.

2021-05-17 15:52 UTC, alan-agius4 commented
@sierkov, thanks for taking this. It’s much appreciated.

2021-05-17 15:54 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +              `render-args-${process.pid}-${shardIndex}.json`,
This would also make it easier for future contributes since we’ll use the same type of workers in all places.

2021-05-28 08:17 UTC, alan-agius4 commented on modules/builders/src/prerender/worker.ts
> +  }
We no longer need to support VE

```suggestion
    return {
      renderModuleFn: renderModule,
      AppServerModuleDef: AppServerModule,
    };
```

2021-05-28 08:18 UTC, alan-agius4 commented on modules/builders/src/prerender/worker.ts
> +}
```suggestion
```

2021-05-28 08:18 UTC, alan-agius4 commented on modules/builders/src/prerender/worker.ts
> +  const { renderModuleFn, AppServerModuleDef } = await getServerBundle(serverBundlePath);
```suggestion
  const { renderModule, AppServerModule } = await import (serverBundlePath);
```

2021-05-28 08:19 UTC, alan-agius4 approved these changes
Thanks for this, LGTM.
Just a couple of small comments.

Also, please squash the commits

2021-05-30 11:27 UTC, sierkov commented
@alan-agius4, thanks for the feedback. I'm mostly done with the squashing, but when I was re-reading through the patch a question arose:
The old code had the below lines to send errors and warnings received from the critical-css-inlining processor to the parent process. I am not quite sure how best to pass this information with jest-workers. Here is my current idea:
1. Print warnings to child's stderr and rely on the parent process for reading and reprinting the warnings (which it does). Lint has complained about my console prints due to no-console rule though. JFYI
2. Throw the first error returned by the processor as an exception. Some information will be lost but the remaining is still sufficient for a fix/rebuild loop to work.

The code lines of the original render.ts in question:
<pre>
    warnings?.forEach((message) => process.send!({ logLevel: 'warn', message }));
    errors?.forEach((message) => process.send!({ logLevel: 'error', message }));
</pre>

Do you have some suggestions regarding this situation?

Also, do you think we need to add a test or the already existing test set should be good enough?
I don't have ideas of simple but effective test cases at the moment, but I'd like to somehow increase my confidence that the new code works well in most use cases.

2021-05-31 10:17 UTC, alan-agius4 commented
>     warnings?.forEach((message) => process.send!({ logLevel: 'warn', message }));
>     errors?.forEach((message) => process.send!({ logLevel: 'error', message }));

2021-05-31 10:29 UTC, alan-agius4 commented
You can return an object literal with errors and warnings from the render function

Worker
```ts
export async function render(
  outputPath: string,
  serverBundlePath: string,
  route: string,
): Promise<{errors?: string[], warnings?:[]> {
}
```

Parent
```ts
const results = await Promise.all(
  routes.map((route) => (worker as any).render(outputPath, serverBundlePath, route)),
);


spinner.stop();
for (const {errors, warnings} of results) {
  errors?.forEach(e => context.logger.errror(e));
  warnings?.forEach(e => context.logger.warning(e));
}
spinner.start();
```

Regarding the test, I think in this case we can leave it out, since doing one will be non-trivial.

2021-06-01 14:44 UTC, sierkov commented
@alan-agius4, thanks! I've updated the patch and also made that in case of errors from css processor prerendering will be considered as failed. LMK

2021-06-02 06:21 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +        const breakingErrors = [];
```suggestion
       let success = true;
```

2021-06-02 06:21 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +          }
```suggestion
          success &&= errrors.length === 0
```

2021-06-02 06:21 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +        }
```suggestion
        if (!success) {
          spinner.fail(`Prerendering routes to ${outputPath} failed. See above.`);
          return { success: false };
        }
```

2021-06-03 03:36 UTC, sierkov commented on modules/builders/src/prerender/index.ts
> +        }
To reduce code duplication in error code paths? Any error within worker goes through the same catch block and to have one less spinner.fail and return call?

2021-06-03 03:37 UTC, sierkov commented on modules/builders/src/prerender/index.ts
> +          }
Would it work for you if I replace the array with a count? That way the error message will be slightly more informative - with the number of blocking issues?

2021-06-03 07:32 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +          }
I am not too strongly about this, but I don't find that adding the count of errors adds anything actionable to the error message. It's up to you really.

2021-06-03 07:39 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +        }
Unless it's a fatal exception, I think it's better not to throw in this case.

It's make it harder to follow code as it's not intuitive without checking the whole code block. What happens with this `throw`? Does this cause a `success: false` or is a fatal exception?

2021-06-05 06:15 UTC, sierkov commented on modules/builders/src/prerender/index.ts
> +        }
Regarding if it's fatal or not, that's a good question:
- This function uses both stop ASAP on error (parameters, server bundle check, service worker generation) and alway process all items (routes prerendering) error-handling strategies. Is there a reason for this?
- In the case, when this is a conscious decision (failed prerendering of some routes is not fatal), than we shouldn't be throwing that error at all. Otherwise, it should be OK to throw an error to indicate that the normal code path shall be interrupted.
Since this depends on the general technical design of the project, I need your input here.

Overall, the error handling in this function is complicated:
1. Both return codes and exceptions are used for error handling. 
2. Both stop-ASAP and keep-on-working error strategies are used.
3. The error information is used additionally to update the spinner's status.

There is a way to simplify it:
1. Use only exceptions inside the function and convert to return codes in the single outer try/catch/finally block.
2. Make spinners use error.message as the fail message instead of custom strings - spinner.fail is only called from catch blocks anyways.
3. Have only one try/catch block per function, so create two new smaller functions for routes prerendering and service worker generation.
However, this may take a few more iteration till we both like the end result. WDYT?

P.S. In the meantime, I updated the pull request to used an error counter and made the spinner calls in try/catch blocks consistent between routes generation and service-worker generation.

2021-06-05 12:41 UTC, sierkov commented on modules/builders/src/prerender/index.ts
> +        }
Also, the latest CI integration test reports an integration failure during "npm run serve:ssr:dev exited with code SIGTERM" complaining about a time out - attached some output below. I cannot reproduce it locally - yarn test finishes successfully in a Docker container. I didn't change any files outside of prerendering, just rebased using the latest master.
Any suggestions out of the top of your head how to debug this?

<pre>
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1] 
[1]   Hello world E2E Tests
[1]     ✗ should display: Hello world!
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1]     ✗ should populate window.location
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1] A Jasmine spec timed out. Resetting the WebDriver Control Flow.
[1]     ✗ stylesheets should be configured to load asynchronously
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
[1]       - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
</pre>

2021-06-07 07:49 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +        }
That looks like a flake.

2021-06-07 08:09 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +        }
Overall, this logic can use a refactor, but the logic is as is, mostly because there are different types of errors.

- Exceptions
   When there is an exception we should exit the process because something when wrong and we don't know how to handle this error, where you might want to have the stack-trace in in the error log file etc...

- Diagnostic errors
   With this type of errors, we know how to handle these errors, we should collect as many diagnostic as possible before exiting so that the user can action these errors are quick as possible.

We should keep the distinction between an exception and a diagnostic error, and where possible the latter should be preferred.

2021-06-07 08:11 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +          warnings?.forEach((e) => context.logger.warn(e));
Before printing anything, when the spinner is running you need to stop and start it, as otherwise it will overlap the  current spinner and cause broken output.


```suggestion
          spinner.stop();
          errors?.forEach((e) => context.logger.error(e));
          warnings?.forEach((e) => context.logger.warn(e));
           spinner.start();
```

2021-06-07 08:12 UTC, alan-agius4 approved these changes
Thanks again, one small last thing

2021-06-11 05:00 UTC, alan-agius4 commented on modules/builders/src/prerender/index.ts
> +          warnings?.forEach((e) => context.logger.warn(e));
Bump!

2021-06-11 05:41 UTC, sierkov commented on modules/builders/src/prerender/index.ts
> +          warnings?.forEach((e) => context.logger.warn(e));
Yep, it's on my list; plan to work on it this weekend.

2021-06-12 12:15 UTC, sierkov commented on modules/builders/src/prerender/index.ts
> +        }
Let's see if I understand you right:
1) Different types of errors - recoverable and non-recoverable (fatal) ones - makes sense. For example, C++ has two exception hierarchies: descendants of std:exception and of std:runtime_error to make it easy to differentiate between the two types of errors in the catch clauses. The only difference is that return codes instead of non-recoverable-exceptions are used. Right?
2) Diagnostic errors - this one can be a little too subtle for me. What's the difference between a warning and a diagnostic error? The closest analogy to diagnostic errors that comes to my mind is again from C++: the compiler collects and prints all compilation errors (won't stop at first one), but won't proceed to the linking phase if there was at least one compilation error. So there is a clear no-pass boundary till which the diagnostic errors are tolerated, but after which even a single error still leads to an abrupt termination of the process.

What's this no-pass boundary in this case? As the code is written right now, it is at service-worker generation: if there are prerendering issues, the service worker is not generated. Also, the next locale from browserResult.outputPaths won't be tried to be prerendered.
Is this fine?

P.S. I have incorporated your suggestion for the correct spinner updates and updated the pull request. LMK if there is any open issue with the code that I need to address.

2021-06-14 05:54 UTC, alan-agius4 approved these changes

2021-06-14 06:02 UTC, merged