docs(@nguniversal/builders): Added Builder Readme Overview
angular/universal pull request #2478
Opened 2021-12-14 16:43 UTC by conradkirschner

A start for documentation about the universal builders. 

Better then WIP I would say, for now. Maybe it gives some overview about how the docs could look like.

2021-12-15 09:00 UTC, alan-agius4 commented on modules/builders/README.md
> +| guessRoutes   | Bolean (default: true)                       | Whether or not the builder should extract routes and guess which paths to render. |          |
```suggestion
| guessRoutes   | Boolean (default: true)                       | Whether or not the builder should extract routes and guess which paths to render. |          |
```

2021-12-15 09:01 UTC, alan-agius4 commented on modules/builders/README.md
> +In any case this Readme.md gets outdated - it's worthy to have a look there!
```suggestion
In any case this Readme.md gets outdated - it's worthy to have a look there!
```

Lets remove this note and make sure to keep the doc updated instead.

2021-12-15 09:02 UTC, alan-agius4 commented on modules/builders/README.md
> +| numProcesses  | Number (min: 1, default: 1)                  | The number of cpus to use. Defaults to all but one.                               |          |
```suggestion
| numProcesses  | number (min: 1, default: 1)                  | The number of cpus to use. Defaults to all but one.                               |          |
```
Not consistence.

2021-12-15 09:03 UTC, alan-agius4 commented on modules/builders/README.md
> +| routesFile    | A Filename - Attention no schema validation! | The path to a file containing routes separated by newlines.                       |          |
```suggestion
| routesFile    | string | The path to a file containing routes separated by newlines.                       |          |
```

There are paths validation in code.

2021-12-15 09:03 UTC, alan-agius4 commented on modules/builders/README.md
> +### Parameter
```suggestion
### Option
```

2021-12-15 09:03 UTC, alan-agius4 commented on modules/builders/README.md
> +### Summary (WIP)
```suggestion
### Description
```

2021-12-15 09:04 UTC, alan-agius4 commented on modules/builders/README.md
> +### Example
```suggestion

```

2021-12-15 09:04 UTC, alan-agius4 commented on modules/builders/README.md
> +WIP
```suggestion

```

2021-12-15 09:04 UTC, alan-agius4 commented on modules/builders/README.md
> +| waitBeforeReload | number                      | Waiting time before reload the page (in Milliseconds)
```suggestion

```

2021-12-15 09:04 UTC, alan-agius4 commented on modules/builders/README.md
> +This builder is the replacement for ng serve, if you develop an Angular Universal App.
```suggestion
This builder is the replacement for ng serve, if you develop an Angular Universal application.
```

2021-12-15 09:05 UTC, alan-agius4 commented on modules/builders/README.md
> +### Summary
```suggestion
### Description
```

2021-12-15 09:05 UTC, alan-agius4 commented on modules/builders/README.md
> +### Parameter
```suggestion
### Options
```

2021-12-15 09:06 UTC, alan-agius4 commented on modules/builders/README.md
> +### Example
```suggestion

```

2021-12-15 09:06 UTC, alan-agius4 commented on modules/builders/README.md
> +WIP
```suggestion
=
```

2021-12-15 09:09 UTC, alan-agius4 commented on modules/builders/README.md
> +This Builder will prerender the routes that you define in a Route-File or as Parameter.
```suggestion
This builder is used to prerender pages of your application. Prerendering is the process where a dynamic page is processed at build time generating static HTML.

For more information about this see: https://angular.io/guide/prerendering

```

2021-12-15 09:12 UTC, alan-agius4 commented on modules/builders/README.md
> +Use this if you want to develop locally an Angular Universal Application
```suggestion
This builder will launch a development server with live-reload capabilities for Angular Universal applications. 
```

2021-12-15 09:12 UTC, alan-agius4 commented on modules/builders/README.md
> +It will hot reload only things that you have changed and trigger a refresh in the browser.
```suggestion

```

2021-12-15 09:12 UTC, alan-agius4 commented on modules/builders/README.md
> +This builder is the replacement for ng serve, if you develop an Angular Universal App.
```suggestion

```
This is not quite right, this builder isn't intended to replace `ng serve` but rather offer a way to serve and watch a universal application.

2021-12-15 09:13 UTC, alan-agius4 commented on modules/builders/README.md
> +### Example
```suggestion

```

2021-12-15 09:13 UTC, alan-agius4 commented on modules/builders/README.md
>  WIP
```suggestion

```

2021-12-15 09:15 UTC, alan-agius4 commented on modules/builders/README.md
> +Builds the browser and server, then renders each route in options.routes and writes them to prerender/<route>/index.html for each output path in the browser result.
```suggestion
This builder is used to prerender pages of your application using the experimental [Clover](../common/clover/README.md) implementation. Prerendering is the process where a dynamic page is processed at build time generating static HTML.

Attention: 
```

2021-12-15 09:15 UTC, alan-agius4 requested changes
Thanks for this. 

Please squash your commits.

2021-12-15 18:20 UTC, conradkirschner commented
@alan-agius4  Thanks for fast reply and suggestion, I just added them and squashed the commits :)

2021-12-15 21:30 UTC, conradkirschner commented on modules/builders/README.md
> +Use this if you don't have any server side Code - as "serverTarget" is not configurable.
Is that correct?

2022-03-07 12:54 UTC, hiepxanh commented
@alan-agius4  I think this docs is full of information, or we just reject ✌️

2022-03-07 13:09 UTC, alan-agius4 approved these changes
LGTM

2022-03-07 13:18 UTC, merged